#!/bin/bash

# File to be placed in /usr/local/sbin/
# Custom script to onboard new users onto RECON
# Funtions:
#	- Create new user with home directory and passwordless login
# 	- Generate and add new SSH keys for inter-node access
# 	- Add user SSH keys for authentication.
# Author: Srikar (aka epoch101),Gurram Siddarth Reddy
# Last modified: 4th Aug, 2022

# $1 - username
# $2 - ssh key
# $3 - Name of the user

MOD_DIR=/usr/local/sbin/useradd_mod

# Check if the username was provided
if ! [ -n "$1" ]; then
	echo "No username provided, exiting..."
	exit
fi
if [ "$2" = "" ]; then                 # If ssh key is an empty string,
    # Getting SSH keys from user
    echo -n "Enter user's SSH keys: "
    read ssh_key
else                                      # Otherwise,
	ssh_key=$2
fi
if [ "$3" = "" ]; then                 # If ssh key is an empty string,
    # Getting SSH keys from user
    echo -n "Enter full name of the user: "
	read FULL_USERNAME
else
	FULL_USERNAME=$3
fi

student='s[1-9][0-9][meca][semi][0-9][0-9][0-9]' # regex for valid student username
faculty='f[0-9][0-9][0-9][0-9]' # regex for valid faculty ID
if [[ ! $1 =~ $student && ! $1 =~ $faculty ]]; then
	echo "Invalid username, exiting..."
	exit	# exit if the username is invalid
fi


# Check if the script is running as root
if [ "$USER" != "root" ]; then
	echo "Script not running as root, exiting..."
	exit
fi

# Create new user with home directory
useradd -m $1 --comment "$FULL_USERNAME"

# Change home permission to 750 for increased privacy
chmod 750 /home/$1

# Get new UID and GID
rUID=$(id $1 -u)
rGID=$(id $1 -g)

# Add user to LDAP
$MOD_DIR/ldif_editors/genLDIF.sh $1 $rUID $rGID

# Generate and add ssh-keys for new user
$MOD_DIR/ssh-keymgmt/gen_newuser_keys.sh -i $1 -u $rUID -g $rGID -k $ssh_key