#!/bin/bash

# File to be placed in /usr/local/sbin/
# Custom script to onboard new users onto RECON
# Funtions:
#	- Create new user with home directory and passwordless login
# 	- Generate and add new SSH keys for inter-node access
# 	- Add user SSH keys for authentication.
# Author: Srikar (aka epoch101),Gurram Siddarth Reddy
# Last modified: 4th Aug, 2022

# $1 - username

MOD_DIR=/usr/local/sbin/useradd_mod

# Check if the username was provided
if ! [ -n "$1" ]; then
	echo "No username provided, exiting..."
	exit
fi

valid='[s][1-9][0-9][u][meca][semi][0-9][0-9][0-9]' # regex for valid username
if [[ ! $1 =~ $valid ]]; then
	echo "Invalid username, exiting..."
	exit # exit if the username is invalid
else
	echo "Valid username, proceeding..."
fi


# Check if the script is running as root
if [ "$USER" != "root" ]; then
	echo "Script not running as root, exiting..."
	exit
fi

# Input user full name
echo -n "Enter full name of the user: "
read FULL_USERNAME

# Create new user with home directory
useradd -m $1 --comment $FULL_USERNAME

# Change home permission to 750 for increased privacy
chmod 750 /home/$1

# Get new UID and GID
UID=$(id $1 -u)
GID=$(id $1 -g)

# Add user to LDAP
$MOD_DIR/ldif_editors/genLDIF.sh $1 $UID $GID

# Generate and add ssh-keys for new user
$MOD_DIR/ssh-keymgmt/gen_newuser_keys.sh $1 $UID $GID